package co.unicauca.restaurante.client.presentation;

import co.unicauca.restaurante.client.domain.clienteService;
import co.unicauca.restaurante.commons.domain.PlatoDia;
import co.unicauca.restaurante.commons.domain.PlatoEspecial;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo Gonzalez, Jhonny Rosero, Edynson Muñoz, James Silva, Jhonfer Ruiz
 */
public class GUIEliminarPlato extends javax.swing.JFrame {
    private clienteService servicioRestaurante;
    private DefaultListModel modelListEspecial;
    private DefaultListModel modelListDia;

    /**
     * Creates new form GUIEliminarPlato
     * @param servicioRestaurante
     */
    public GUIEliminarPlato(clienteService servicioRestaurante) {
        this.initComponents();
        this.setLocationRelativeTo(null);
        this.servicioRestaurante = servicioRestaurante;
        this.modelListEspecial = new DefaultListModel();
        this.modelListDia = new DefaultListModel();
        this.listPlatoDia.setModel(this.modelListDia);
        this.listPlatoEspecial.setModel(this.modelListEspecial);
        try {
            this.listarMenuDia();
            this.listarMenuEspecial();
        } catch (Exception ex) {
            Logger.getLogger(GUIListar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        scrollPnlPlatoDia = new javax.swing.JScrollPane();
        listPlatoDia = new javax.swing.JList<>();
        scrollPnlPlatoEspecial = new javax.swing.JScrollPane();
        listPlatoEspecial = new javax.swing.JList<>();
        lblPlatoEspecial = new javax.swing.JLabel();
        btnEliminarPlatoEspecial = new javax.swing.JButton();
        lblPlatoDia = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        txtEliminarPlaEsp = new javax.swing.JTextField();
        btnEliminarPlatoDia = new javax.swing.JButton();
        txtEliminarPlaDia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 450));
        setPreferredSize(new java.awt.Dimension(817, 370));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        listPlatoDia.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listPlatoDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPlatoDiaMouseClicked(evt);
            }
        });
        scrollPnlPlatoDia.setViewportView(listPlatoDia);

        getContentPane().add(scrollPnlPlatoDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 330, 210));

        listPlatoEspecial.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listPlatoEspecial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPlatoEspecialMouseClicked(evt);
            }
        });
        scrollPnlPlatoEspecial.setViewportView(listPlatoEspecial);

        getContentPane().add(scrollPnlPlatoEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 330, 210));

        lblPlatoEspecial.setBackground(new java.awt.Color(153, 0, 0));
        lblPlatoEspecial.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblPlatoEspecial.setForeground(new java.awt.Color(255, 255, 255));
        lblPlatoEspecial.setText("Platos Especiales");
        lblPlatoEspecial.setOpaque(true);
        getContentPane().add(lblPlatoEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        btnEliminarPlatoEspecial.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminarPlatoEspecial.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnEliminarPlatoEspecial.setText("Eliminar");
        btnEliminarPlatoEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPlatoEspecialActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarPlatoEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 160, 30));

        lblPlatoDia.setBackground(new java.awt.Color(153, 0, 0));
        lblPlatoDia.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        lblPlatoDia.setForeground(new java.awt.Color(255, 255, 255));
        lblPlatoDia.setText("Platos del dia");
        lblPlatoDia.setOpaque(true);
        getContentPane().add(lblPlatoDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        lblTitle.setBackground(new java.awt.Color(153, 0, 0));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ELIMINAR PLATO");
        lblTitle.setOpaque(true);
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, 410));

        txtEliminarPlaEsp.setText("Ingrese id del plato a eliminar");
        txtEliminarPlaEsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEliminarPlaEspMouseClicked(evt);
            }
        });
        txtEliminarPlaEsp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEliminarPlaEspKeyTyped(evt);
            }
        });
        getContentPane().add(txtEliminarPlaEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 240, 30));

        btnEliminarPlatoDia.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminarPlatoDia.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnEliminarPlatoDia.setText("Eliminar");
        btnEliminarPlatoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPlatoDiaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarPlatoDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 160, 30));

        txtEliminarPlaDia.setText("Ingrese id del plato a eliminar");
        txtEliminarPlaDia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEliminarPlaDiaMouseClicked(evt);
            }
        });
        txtEliminarPlaDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEliminarPlaDiaKeyTyped(evt);
            }
        });
        getContentPane().add(txtEliminarPlaDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 240, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarPlatoEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPlatoEspecialActionPerformed
        if (this.txtEliminarPlaEsp.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "No digito ningun id");
        }else{
            int idPlaE = Integer.parseInt(this.txtEliminarPlaEsp.getText());
            try {
                String resultado = this.servicioRestaurante.deletePlatoEspecial(idPlaE);
                if (resultado.equals("FALLO")) {
                    JOptionPane.showMessageDialog(null, "El id del plato es incorrecto");
                } else {
                    JOptionPane.showMessageDialog(null, "Plato eliminado con exito");                
                    this.listarMenuEspecial();
                }
            } catch (Exception ex) {
                Logger.getLogger(GUIEliminarPlato.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        this.txtEliminarPlaEsp.setText("Ingrese id del plato a eliminar");
    }//GEN-LAST:event_btnEliminarPlatoEspecialActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        GUIMenuAdmin ins = new GUIMenuAdmin(this.servicioRestaurante);
        ins.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtEliminarPlaEspKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEliminarPlaEspKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txtEliminarPlaEspKeyTyped

    private void btnEliminarPlatoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPlatoDiaActionPerformed
        if (this.txtEliminarPlaDia.getText().length() == 0) {
            JOptionPane.showMessageDialog(null, "No digito ningun id");
        }else{
            int idPlaD = Integer.parseInt(this.txtEliminarPlaDia.getText());
            try {
                String resultado = this.servicioRestaurante.deletePlatoDia(idPlaD);
                if (resultado.equals("FALLO")) {
                    JOptionPane.showMessageDialog(null, "El id del plato es incorrecto");
                } else {
                    JOptionPane.showMessageDialog(null, "Plato eliminado con exito");
                    this.listarMenuDia();
                }
            } catch (Exception ex) {
                Logger.getLogger(GUIEliminarPlato.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        this.txtEliminarPlaDia.setText("Ingrese id del plato a eliminar");
    }//GEN-LAST:event_btnEliminarPlatoDiaActionPerformed

    private void txtEliminarPlaDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEliminarPlaDiaKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txtEliminarPlaDiaKeyTyped

    private void txtEliminarPlaDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEliminarPlaDiaMouseClicked
        this.txtEliminarPlaDia.setText("");
    }//GEN-LAST:event_txtEliminarPlaDiaMouseClicked

    private void txtEliminarPlaEspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEliminarPlaEspMouseClicked
        this.txtEliminarPlaEsp.setText("");
    }//GEN-LAST:event_txtEliminarPlaEspMouseClicked

    private void listPlatoDiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPlatoDiaMouseClicked
        this.validaFieldELiminarPlatoDia();
    }//GEN-LAST:event_listPlatoDiaMouseClicked

    private void listPlatoEspecialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPlatoEspecialMouseClicked
        this.validaFieldEliminarPlatoEspecial();
    }//GEN-LAST:event_listPlatoEspecialMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.validaFieldELiminarPlatoDia();
        this.validaFieldEliminarPlatoEspecial();
    }//GEN-LAST:event_formMouseClicked
    
    private void validaFieldELiminarPlatoDia(){
        if (this.txtEliminarPlaDia.getText().length() == 0) {
            this.txtEliminarPlaDia.setText("Ingrese id del plato a eliminar");
        }
    }
    
    private void validaFieldEliminarPlatoEspecial(){
        if(this.txtEliminarPlaEsp.getText().length() == 0){
            this.txtEliminarPlaEsp.setText("Ingrese id del plato a eliminar");
        }
    }
    
    private void listarMenuEspecial()throws Exception{
        int resId = 1;
        List<PlatoEspecial> lsEspecial = this.servicioRestaurante.listarMenuEspecial(resId);
        this.modelListEspecial.clear();
        for (PlatoEspecial lse : lsEspecial) {
            this.modelListEspecial.addElement("ID: " + lse.getId() + " NOMBRE: " + lse.getNombre()
                    + " DESCRIPCION: " + lse.getDescripcion() + " PRECIO: " + lse.getPrecio());
        }
    }

    private void listarMenuDia() throws Exception{
        int resId = 1;
        List<PlatoDia> lsDia = this.servicioRestaurante.listarMenuDia(resId);
        this.modelListDia.clear();
        for (PlatoDia ls : lsDia) {
            this.modelListDia.addElement("ID: " + ls.getId() + " NOMBRE: " + ls.getNombre()
                    + " DIA SEMANA: " + ls.getDiaSemana().name() + " DESCRIPCION: " + ls.getDescripcion()
                    + " PRECIO: " + ls.getPrecio() + " ENTRADA: " + ls.getEntrada()
                    + " PRINCIPIO" + ls.getPrincipio() + " CARNE: " + ls.getCarne() + " BEBIDA: " + ls.getBebida());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminarPlatoDia;
    private javax.swing.JButton btnEliminarPlatoEspecial;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblPlatoDia;
    private javax.swing.JLabel lblPlatoEspecial;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> listPlatoDia;
    private javax.swing.JList<String> listPlatoEspecial;
    private javax.swing.JScrollPane scrollPnlPlatoDia;
    private javax.swing.JScrollPane scrollPnlPlatoEspecial;
    private javax.swing.JTextField txtEliminarPlaDia;
    private javax.swing.JTextField txtEliminarPlaEsp;
    // End of variables declaration//GEN-END:variables
}
