package co.unicauca.restaurante.client.presentation;

import co.unicauca.restaurante.client.domain.clienteService;
import co.unicauca.restaurante.commons.domain.PlatoDia;
import co.unicauca.restaurante.commons.domain.PlatoEspecial;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Camilo Gonzalez, Jhonny Rosero, Edynson Muñoz, James Silva, Jhonfer Ruiz
 */
public class GUIListar extends javax.swing.JFrame {   
    private clienteService servicioRestaurante;  
    private DefaultListModel modelListDia;
    private DefaultListModel modelListEspecial;
    private String user;
    
    /**
     * Creates new form GUIListar
     * @param servicioRestaurante
     */
    public GUIListar(clienteService servicioRestaurante, String user){
        this.initComponents();
        this.setLocationRelativeTo(null);
        this.modelListDia = new DefaultListModel();
        this.modelListEspecial = new DefaultListModel();
        this.ListDia.setModel(this.modelListDia);
        this.ListEspecial.setModel(this.modelListEspecial);
        this.servicioRestaurante = servicioRestaurante;
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        scrollPnlMenuEsp = new javax.swing.JScrollPane();
        ListEspecial = new javax.swing.JList<>();
        btnListar = new javax.swing.JButton();
        lblMenuDia = new javax.swing.JLabel();
        lblMenuEspecial = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        scrollPnlMenuDia = new javax.swing.JScrollPane();
        ListDia = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 450));
        setPreferredSize(new java.awt.Dimension(817, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        lblTitle.setBackground(new java.awt.Color(153, 0, 0));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("LISTA DE PLATOS");
        lblTitle.setOpaque(true);
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        ListEspecial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollPnlMenuEsp.setViewportView(ListEspecial);

        getContentPane().add(scrollPnlMenuEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 360, 240));

        btnListar.setBackground(new java.awt.Color(153, 0, 0));
        btnListar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("Ver platos");
        btnListar.setBorderPainted(false);
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        getContentPane().add(btnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 210, -1));

        lblMenuDia.setBackground(new java.awt.Color(153, 0, 0));
        lblMenuDia.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblMenuDia.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuDia.setText("Menu Dia");
        lblMenuDia.setOpaque(true);
        getContentPane().add(lblMenuDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 90, -1));

        lblMenuEspecial.setBackground(new java.awt.Color(153, 0, 0));
        lblMenuEspecial.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblMenuEspecial.setForeground(new java.awt.Color(255, 255, 255));
        lblMenuEspecial.setText("Menu Especial");
        lblMenuEspecial.setOpaque(true);
        getContentPane().add(lblMenuEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 800, 430));

        ListDia.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPnlMenuDia.setViewportView(ListDia);

        getContentPane().add(scrollPnlMenuDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 340, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        if (this.user.equals("Administrador")) {
            GUIMenuAdmin insAdmin = new GUIMenuAdmin(this.servicioRestaurante);
            insAdmin.setVisible(true);
        }else{
            GUILogin ins = new GUILogin();
            ins.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        try {
            this.listar();
        } catch (Exception ex) {
            Logger.getLogger(GUIListar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnListarActionPerformed
    
    /**
     * Lista el menu del dia por platos de este y el menu especial.
     * 
     * @throws Exception 
     */
    public void listar() throws Exception {
        int resId = 1;
        List<PlatoDia> lsDia = this.servicioRestaurante.listarMenuDia(resId);
        List<PlatoEspecial> lsEspecial = this.servicioRestaurante.listarMenuEspecial(resId);
        if (lsDia.size() > 0) {
            this.modelListDia.removeAllElements();
            for (PlatoDia ls : lsDia) {
                this.modelListDia.addElement("ID: " + ls.getId() + " NOMBRE: " + ls.getNombre()
                        + " DIA SEMANA: " + ls.getDiaSemana().name() + " DESCRIPCION: " + ls.getDescripcion()
                        + " PRECIO: " + ls.getPrecio() + " ENTRADA: " + ls.getEntrada()
                        + " PRINCIPIO" + ls.getPrincipio() + " CARNE: " + ls.getCarne() + " BEBIDA: " + ls.getBebida());
            }
        }
        if (lsEspecial.size() > 0) {
            this.modelListEspecial.removeAllElements();
            for (PlatoEspecial lse : lsEspecial) {
                this.modelListEspecial.addElement("ID: " + lse.getId() + " NOMBRE: " + lse.getNombre()
                        + " DESCRIPCION: " + lse.getDescripcion() + " PRECIO: " + lse.getPrecio());
            }
        }
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListDia;
    private javax.swing.JList<String> ListEspecial;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblMenuDia;
    private javax.swing.JLabel lblMenuEspecial;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JScrollPane scrollPnlMenuDia;
    private javax.swing.JScrollPane scrollPnlMenuEsp;
    // End of variables declaration//GEN-END:variables
}
