package co.unicauca.restaurante.client.presentation;

import co.unicauca.restaurante.client.access.Factory;
import co.unicauca.restaurante.client.access.IClienteAccess;
import co.unicauca.restaurante.client.domain.clienteService;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo Gonzalez, Jhonny Rosero, Edynson Muñoz, James Silva, Jhonfer Ruiz
 */
public class GUILogin extends javax.swing.JFrame {
    private final IClienteAccess service;
    private final clienteService servicioRestaurante;
    
    /**
     * Creates new form GUILogin
     */
    public GUILogin() {
        this.initComponents();
        this.setLocationRelativeTo(null);
        this.service = Factory.getInstance().getClienteService();
        this.servicioRestaurante = new clienteService(this.service);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxTypeUser = new javax.swing.JComboBox<>();
        pwdUser = new javax.swing.JPasswordField();
        lblTypeUser = new javax.swing.JLabel();
        lblPasswordUser = new javax.swing.JLabel();
        btnIniciarSesion = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxTypeUser.setEditable(true);
        cbxTypeUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Administrador", "Cliente" }));
        getContentPane().add(cbxTypeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 340, 40));

        pwdUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(pwdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 340, 40));

        lblTypeUser.setBackground(new java.awt.Color(153, 0, 0));
        lblTypeUser.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblTypeUser.setForeground(new java.awt.Color(255, 255, 255));
        lblTypeUser.setText("Seleccione el tipo de usuario:");
        lblTypeUser.setOpaque(true);
        getContentPane().add(lblTypeUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 190, -1));

        lblPasswordUser.setBackground(new java.awt.Color(153, 0, 0));
        lblPasswordUser.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lblPasswordUser.setForeground(new java.awt.Color(255, 255, 255));
        lblPasswordUser.setText("Contraseña:");
        lblPasswordUser.setOpaque(true);
        getContentPane().add(lblPasswordUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        btnIniciarSesion.setBackground(new java.awt.Color(153, 0, 0));
        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("INICIAR SESIÓN");
        btnIniciarSesion.setBorder(null);
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 220, 40));

        lblTitle.setBackground(new java.awt.Color(153, 0, 0));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("MOBICELL");
        lblTitle.setOpaque(true);
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 65));

        lblFondo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        lblFondo.setText(".");
        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 650, 330));
        lblFondo.getAccessibleContext().setAccessibleParent(lblFondo);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        String opcion = this.cbxTypeUser.getSelectedItem().toString();
        switch (opcion) {
            case "Administrador":
                    this.setVisible(false);
                    GUIMenuAdmin insAdmin = new GUIMenuAdmin(this.servicioRestaurante);
                    insAdmin.setVisible(true);
                    break;
            case "Cliente":
                    this.setVisible(false);
                    GUIListar insListar = new GUIListar(this.servicioRestaurante, "Cliente");
                    insListar.setVisible(true);
                    break;
            default:
                JOptionPane.showMessageDialog(null, "Por favor elija un tipo de usuario");
                break;
        }
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUILogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JComboBox<String> cbxTypeUser;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblPasswordUser;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTypeUser;
    private javax.swing.JPasswordField pwdUser;
    // End of variables declaration//GEN-END:variables
}
