package co.unicauca.restaurante.client.presentation;

import co.unicauca.restaurante.client.domain.clienteService;
import co.unicauca.restaurante.commons.domain.PlatoEspecial;
import co.unicauca.restaurante.commons.infra.Utilities;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo Gonzalez, Jhonny Rosero, Edynson Muñoz, James Silva, Jhonfer Ruiz
 */
public class GUIModifPlatoEsp extends javax.swing.JFrame {
    private clienteService servicioRestaurante;
    private DefaultListModel modelListEspecial;
    
    /**
     * Creates new form GUIModifPlatoEsp
     * @param servicioRestaurante
     */
    public GUIModifPlatoEsp(clienteService servicioRestaurante) {
        this.initComponents();
        this.setLocationRelativeTo(null);
        this.btnActualizar.setEnabled(false);
        this.modelListEspecial = new DefaultListModel();
        this.listPlatoEspecial.setModel(this.modelListEspecial);
        this.servicioRestaurante = servicioRestaurante;
        try {
            this.listar();
        } catch (Exception ex) {
            Logger.getLogger(GUIModifPlatoEsp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigoPlatEsp = new javax.swing.JLabel();
        txtCodigoPlatEsp = new javax.swing.JTextField();
        lblTypeModified = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();
        txtFieldModified = new javax.swing.JTextField();
        lblFieldModified = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPlatoEspecial = new javax.swing.JList<>();
        btnActualizar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 450));
        setPreferredSize(new java.awt.Dimension(950, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigoPlatEsp.setBackground(new java.awt.Color(153, 0, 0));
        lblCodigoPlatEsp.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblCodigoPlatEsp.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoPlatEsp.setText("Codigo del Plato");
        lblCodigoPlatEsp.setOpaque(true);
        getContentPane().add(lblCodigoPlatEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtCodigoPlatEsp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoPlatEspKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoPlatEspKeyTyped(evt);
            }
        });
        getContentPane().add(txtCodigoPlatEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 180, 40));

        lblTypeModified.setBackground(new java.awt.Color(153, 0, 0));
        lblTypeModified.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblTypeModified.setForeground(new java.awt.Color(255, 255, 255));
        lblTypeModified.setText("Seleccione que desea modificar");
        lblTypeModified.setOpaque(true);
        getContentPane().add(lblTypeModified, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Nombre", "Descripcion", "Precio" }));
        cbxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTipoItemStateChanged(evt);
            }
        });
        getContentPane().add(cbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 260, 40));

        txtFieldModified.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFieldModifiedKeyReleased(evt);
            }
        });
        getContentPane().add(txtFieldModified, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 220, 40));

        lblFieldModified.setBackground(new java.awt.Color(153, 0, 0));
        lblFieldModified.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblFieldModified.setForeground(new java.awt.Color(255, 255, 255));
        lblFieldModified.setText("Modificación");
        lblFieldModified.setOpaque(true);
        getContentPane().add(lblFieldModified, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        listPlatoEspecial.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listPlatoEspecial);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 600, 280));

        btnActualizar.setBackground(new java.awt.Color(153, 0, 0));
        btnActualizar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 363, 160, 30));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        lblTitle.setBackground(new java.awt.Color(153, 0, 0));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("MODIFICAR PLATO ESPECIAL");
        lblTitle.setOpaque(true);
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        GUIMenuModificar ins = new GUIMenuModificar(this.servicioRestaurante);
        ins.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * lista de la base de datos los platos
     * @throws Exception 
     */
    private void listar() throws Exception {
        int resId = 1;
        List<PlatoEspecial> lista = this.servicioRestaurante.listarMenuEspecial(resId);
        this.modelListEspecial.clear();
        for (PlatoEspecial lse : lista) {
            this.modelListEspecial.addElement("ID: " + lse.getId()
                    + " NOMBRE: " + lse.getNombre()
                    + " DESCRIPCION: " + lse.getDescripcion()
                    + " PRECIO: " + lse.getPrecio());
        }
    }
    
    /**
     * envia la solicitud al servidor para hacer una operacion update
     * @param evt 
     */
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        boolean respuesta = false;
        int id = Integer.parseInt(this.txtCodigoPlatEsp.getText());
        String valor = this.txtFieldModified.getText();
        String atributo=null;
        switch (this.cbxTipo.getSelectedIndex()) {
            case 1: atributo = "PESP_NOMBRE"; break;
            case 2: atributo = "PESP_DESCRIPCION"; break;
            case 3: atributo = "PESP_PRECIO"; break;
            default: break;
        }
        if(atributo.equals("PESP_PRECIO")){
            if(!Utilities.isNumeric(valor)){
                JOptionPane.showMessageDialog(null, "el precio debe contener valores numericos, VERIFIQUE");
                return;
            }
        }
        try {
            respuesta = this.servicioRestaurante.updatePlatoEspecial(id, atributo, valor);
            if(!respuesta){
                JOptionPane.showMessageDialog(null, "por favor verifique los valores, no se encuentra el item");
            }else{
                this.listar();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ha fallado la peticion, intentelo nuevamente");
            Logger.getLogger(GUIModificarPlatoDia.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.txtCodigoPlatEsp.setText(null);
        this.cbxTipo.setSelectedIndex(0);
        this.txtFieldModified.setText(null);
        this.btnActualizar.setEnabled(false);
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * impide que se digiten caracteres no numericos
     * @param evt 
     */
    private void txtCodigoPlatEspKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPlatEspKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txtCodigoPlatEspKeyTyped

    /**
     * se despliega al digitar en la caja de texto
     * @param evt 
     */
    private void txtCodigoPlatEspKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPlatEspKeyReleased
        this.habilitarBtnActualizar();
    }//GEN-LAST:event_txtCodigoPlatEspKeyReleased

    /**
     * se depliega al digitar en caja de texto
     * @param evt 
     */
    private void txtFieldModifiedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFieldModifiedKeyReleased
        this.habilitarBtnActualizar();
    }//GEN-LAST:event_txtFieldModifiedKeyReleased

    /**
     * se activa al momento de elegir una opcion en el combo box
     * @param evt 
     */
    private void cbxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTipoItemStateChanged
        this.habilitarBtnActualizar();
    }//GEN-LAST:event_cbxTipoItemStateChanged

    /**
     * verifica que los campos esten diligenciados, si es activa el boton
     */
    private void habilitarBtnActualizar(){
        if(this.txtCodigoPlatEsp.getText().isEmpty() 
                || this.txtFieldModified.getText().isEmpty()
                || this.cbxTipo.getSelectedIndex() == 0){
            this.btnActualizar.setEnabled(false);
        }else{
            this.btnActualizar.setEnabled(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigoPlatEsp;
    private javax.swing.JLabel lblFieldModified;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTypeModified;
    private javax.swing.JList<String> listPlatoEspecial;
    private javax.swing.JTextField txtCodigoPlatEsp;
    private javax.swing.JTextField txtFieldModified;
    // End of variables declaration//GEN-END:variables
}
