package co.unicauca.restaurante.client.presentation;

import co.unicauca.restaurante.client.domain.clienteService;

/**
 *
 * @author Camilo Gonzalez, Jhonny Rosero, Edynson Muñoz, James Silva, Jhonfer Ruiz
 */
public class GUIMenuModificar extends javax.swing.JFrame {
    private clienteService servicioRestaurante;
    
    /**
     * Creates new form MenuModificar
     * @param servicioRestaurante
     */
    public GUIMenuModificar(clienteService servicioRestaurante) {
        this.initComponents();
        this.setLocationRelativeTo(null);
        this.servicioRestaurante = servicioRestaurante;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSubtitle = new javax.swing.JLabel();
        btnModPlatD = new javax.swing.JButton();
        btnModPlatE = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSubtitle.setBackground(new java.awt.Color(153, 0, 0));
        lblSubtitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitle.setText("Cual Plato desea Modificar?");
        lblSubtitle.setOpaque(true);
        getContentPane().add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        btnModPlatD.setBackground(new java.awt.Color(255, 255, 255));
        btnModPlatD.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        btnModPlatD.setText("Plato del Dia");
        btnModPlatD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnModPlatD.setBorderPainted(false);
        btnModPlatD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModPlatDActionPerformed(evt);
            }
        });
        getContentPane().add(btnModPlatD, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 280, 160));

        btnModPlatE.setBackground(new java.awt.Color(255, 255, 255));
        btnModPlatE.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        btnModPlatE.setText("Plato Especial");
        btnModPlatE.setBorderPainted(false);
        btnModPlatE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModPlatEActionPerformed(evt);
            }
        });
        getContentPane().add(btnModPlatE, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 290, 160));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        lblTitle.setBackground(new java.awt.Color(153, 0, 0));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("MODIFICAR PLATOS");
        lblTitle.setOpaque(true);
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -10, 780, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModPlatDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModPlatDActionPerformed
        this.setVisible(false);
        GUIModificarPlatoDia ins = new GUIModificarPlatoDia(this.servicioRestaurante);
        ins.setVisible(true);
    }//GEN-LAST:event_btnModPlatDActionPerformed

    private void btnModPlatEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModPlatEActionPerformed
        this.setVisible(false);
        GUIModifPlatoEsp ins = new GUIModifPlatoEsp(this.servicioRestaurante);
        ins.setVisible(true);
    }//GEN-LAST:event_btnModPlatEActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        GUIMenuAdmin ins = new GUIMenuAdmin(this.servicioRestaurante);
        ins.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModPlatD;
    private javax.swing.JButton btnModPlatE;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
