package co.unicauca.restaurante.client.presentation;

import co.unicauca.restaurante.client.domain.clienteService;
import co.unicauca.restaurante.commons.domain.PlatoDia;
import co.unicauca.restaurante.commons.infra.Utilities;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo Gonzalez, Jhonny Rosero, Edynson Muñoz, James Silva, Jhonfer Ruiz
 */
public class GUIModificarPlatoDia extends javax.swing.JFrame {
    private clienteService servicioRestaurante;
    private DefaultListModel modelListEspecial;
    
    /**
     * Creates new form GUIModificarPlato
     * @param servicioRestaurante
     */
    public GUIModificarPlatoDia(clienteService servicioRestaurante) {
        this.initComponents();
        this.setLocationRelativeTo(null);
        this.btnActualizar.setEnabled(false);
        this.modelListEspecial=new DefaultListModel();
        this.listPlato.setModel(modelListEspecial);
        this.servicioRestaurante=servicioRestaurante;   
        try {
            this.listar();
        } catch (Exception ex) {
            Logger.getLogger(GUIModificarPlatoDia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigoPlatDia = new javax.swing.JLabel();
        lblTypeModified = new javax.swing.JLabel();
        cbxTypeModified = new javax.swing.JComboBox<>();
        txtCodigoPlatDia = new javax.swing.JTextField();
        txtValueModified = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        scrollPnlPlatoDia = new javax.swing.JScrollPane();
        listPlato = new javax.swing.JList<>();
        lblValueModified = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigoPlatDia.setBackground(new java.awt.Color(153, 0, 0));
        lblCodigoPlatDia.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblCodigoPlatDia.setForeground(new java.awt.Color(255, 255, 255));
        lblCodigoPlatDia.setText("Codigo del plato");
        lblCodigoPlatDia.setOpaque(true);
        getContentPane().add(lblCodigoPlatDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        lblTypeModified.setBackground(new java.awt.Color(153, 0, 0));
        lblTypeModified.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblTypeModified.setForeground(new java.awt.Color(255, 255, 255));
        lblTypeModified.setText("Seleccione que desea Modificar");
        lblTypeModified.setOpaque(true);
        getContentPane().add(lblTypeModified, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        cbxTypeModified.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Nombre", "Descripcion", "Entrada", "Principio", "Bebida", "Carne", "Precio" }));
        cbxTypeModified.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTypeModifiedItemStateChanged(evt);
            }
        });
        getContentPane().add(cbxTypeModified, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 260, 40));
        cbxTypeModified.getAccessibleContext().setAccessibleName("");

        txtCodigoPlatDia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCodigoPlatDia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoPlatDiaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoPlatDiaKeyTyped(evt);
            }
        });
        getContentPane().add(txtCodigoPlatDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 190, 40));

        txtValueModified.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtValueModified.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtValueModifiedKeyReleased(evt);
            }
        });
        getContentPane().add(txtValueModified, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 190, 40));

        btnActualizar.setBackground(new java.awt.Color(204, 0, 0));
        btnActualizar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 160, 30));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setName(""); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        listPlato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listPlato.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPnlPlatoDia.setViewportView(listPlato);

        getContentPane().add(scrollPnlPlatoDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 800, 280));

        lblValueModified.setBackground(new java.awt.Color(153, 0, 0));
        lblValueModified.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblValueModified.setForeground(new java.awt.Color(255, 255, 255));
        lblValueModified.setText("Modificación");
        lblValueModified.setOpaque(true);
        getContentPane().add(lblValueModified, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        lblTitle.setBackground(new java.awt.Color(153, 0, 0));
        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("MODIFICAR PLATO DEL DIA");
        lblTitle.setOpaque(true);
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        GUIMenuModificar ins = new GUIMenuModificar(this.servicioRestaurante);
        ins.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * al ser pulsado, valida los datos, y envia la solicitud
     * @param evt 
     */
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        boolean respuesta = false;
        int id =Integer.parseInt(this.txtCodigoPlatDia.getText());
        String valor = this.txtValueModified.getText();
        String atributo = "";
        switch (this.cbxTypeModified.getSelectedIndex()) {
            case 1: atributo = "PDIA_NOMBRE"; break;
            case 2: atributo = "PDIA_DESCRIPCION"; break;
            case 3: atributo = "PDIA_ENTRADA"; break;
            case 4: atributo = "PDIA_PRINCIPIO"; break;
            case 5: atributo = "PDIA_BEBIDA"; break;
            case 6: atributo = "PDIA_CARNE"; break;
            case 7: atributo = "PDIA_PRECIO"; break;
            default: break;
        }
        if(atributo.equals("PDIA_PRECIO")){
            if(!Utilities.isNumeric(valor)){
                JOptionPane.showMessageDialog(null, "el precio debe contener valores numericos, VERIFIQUE");
                return;
            }
        }
        try {
            respuesta = this.servicioRestaurante.updatePlatoDia(id, atributo, valor);
            if(!respuesta){
                JOptionPane.showMessageDialog(null, "verifique los datos, ITEM NO ENCONTRADO");
            }else{
                this.listar();
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "ha fallado el servicio, intentelo de nuevo");
        }
        this.txtCodigoPlatDia.setText(null);
        this.cbxTypeModified.setSelectedIndex(0);
        this.txtValueModified.setText(null);
        this.btnActualizar.setEnabled(false);
    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * lista en la interfaz una base de datos
     * @throws Exception 
     */
    private void listar() throws Exception{
        int resId=1;
        List<PlatoDia> lista = this.servicioRestaurante.listarMenuDia(resId);
        this.modelListEspecial.clear();
        lista.forEach(lse -> {
            this.modelListEspecial.addElement("ID: " + lse.getId() 
                    + " NOMBRE: " + lse.getNombre()
                    + " DESCRIPCION: " + lse.getDescripcion()
                    + " PRECIO: " + lse.getPrecio()
                    + " ENTRADA: "+lse.getEntrada() 
                    + " PRINCIPIO: "+lse.getPrincipio()
                    + " CARNE: "+lse.getCarne()
                    + " BEBIDA: "+lse.getBebida()
                    + " DIA: "+lse.getDiaSemana());
        });
    }
    /**
     * valida que se ingresen solo caracteres del 0 al 9 (numeros)
     * @param evt 
     */
    private void txtCodigoPlatDiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPlatDiaKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txtCodigoPlatDiaKeyTyped

    /**
     * se despliega al momento de digitar en la caja de texto, y verifica si estan llenos los parametros
     * @param evt 
     */
    private void txtCodigoPlatDiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPlatDiaKeyReleased
        this.habilitarBtnActualizar();
    }//GEN-LAST:event_txtCodigoPlatDiaKeyReleased

    /**
     * se activa al momento de ingresar caracteres a la caja de texto
     * @param evt 
     */
    private void txtValueModifiedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValueModifiedKeyReleased
        this.habilitarBtnActualizar();
    }//GEN-LAST:event_txtValueModifiedKeyReleased

    /**
     * se activa al momento de cambiar el estado del combo box
     * @param evt 
     */
    private void cbxTypeModifiedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTypeModifiedItemStateChanged
        this.habilitarBtnActualizar();
    }//GEN-LAST:event_cbxTypeModifiedItemStateChanged

    /**
     * verifica si ya es momento de activar el boton, solo cuando se han digitado y seleccionado los datos
     */
    private void habilitarBtnActualizar(){
        if(this.txtCodigoPlatDia.getText().isEmpty() 
                || this.txtValueModified.getText().isEmpty()
                || this.cbxTypeModified.getSelectedIndex() == 0){
            this.btnActualizar.setEnabled(false);
        }else{
            this.btnActualizar.setEnabled(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxTypeModified;
    private javax.swing.JLabel lblCodigoPlatDia;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTypeModified;
    private javax.swing.JLabel lblValueModified;
    private javax.swing.JList<String> listPlato;
    private javax.swing.JScrollPane scrollPnlPlatoDia;
    private javax.swing.JTextField txtCodigoPlatDia;
    private javax.swing.JTextField txtValueModified;
    // End of variables declaration//GEN-END:variables
}
