package co.unicauca.restaurante.client.presentation;

import co.unicauca.restaurante.client.domain.clienteService;
import co.unicauca.restaurante.commons.domain.MenuEspecial;
import co.unicauca.restaurante.commons.domain.PlatoEspecial;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo Gonzalez, Jhonny Rosero, Edynson Muñoz, James Silva, Jhonfer Ruiz
 */
public class GUIRegPlato extends javax.swing.JFrame { 
    private clienteService servicioRestaurante;
    private DefaultListModel modelListEspecial;
    
     /**
     * Creates new form GUIRegPlato
     * @param servicioRestaurante
     */
    public GUIRegPlato(clienteService servicioRestaurante) {
        this.initComponents();
        this.setLocationRelativeTo(null);
        this.modelListEspecial = new DefaultListModel();
        this.listPlatoEspecial.setModel(this.modelListEspecial);
        this.servicioRestaurante = servicioRestaurante;
        try {
            this.listar();
        } catch (Exception ex) {
            Logger.getLogger(GUIRegPlato.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        cbxTipoPlato = new javax.swing.JComboBox<>();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        lblDescription = new javax.swing.JLabel();
        lblNombrePlate = new javax.swing.JLabel();
        lblTypePrecio = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblCodigoPlate = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        lblTypePlate = new javax.swing.JLabel();
        scrollPnlPlatEspecial = new javax.swing.JScrollPane();
        listPlatoEspecial = new javax.swing.JList<>();
        lblContenTitle = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(817, 370));
        setPreferredSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("REGISTRAR PLATO");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        cbxTipoPlato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plato Especial", "Plato del Dia" }));
        cbxTipoPlato.setToolTipText("Plato Especial");
        cbxTipoPlato.setBorder(null);
        cbxTipoPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoPlatoActionPerformed(evt);
            }
        });
        getContentPane().add(cbxTipoPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 170, 40));

        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 160, 30));

        txtDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 470, 50));

        btnRegistrar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrar.setPreferredSize(new java.awt.Dimension(100, 200));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 210, 50));

        lblDescription.setBackground(new java.awt.Color(255, 255, 255));
        lblDescription.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(153, 0, 0));
        lblDescription.setText("Descripción:");
        lblDescription.setOpaque(true);
        getContentPane().add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        lblNombrePlate.setBackground(new java.awt.Color(255, 255, 255));
        lblNombrePlate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblNombrePlate.setForeground(new java.awt.Color(153, 0, 0));
        lblNombrePlate.setText("Nombre:");
        lblNombrePlate.setOpaque(true);
        getContentPane().add(lblNombrePlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        lblTypePrecio.setBackground(new java.awt.Color(255, 255, 255));
        lblTypePrecio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblTypePrecio.setForeground(new java.awt.Color(153, 0, 0));
        lblTypePrecio.setText("Valor:");
        lblTypePrecio.setOpaque(true);
        getContentPane().add(lblTypePrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, -1, -1));

        txtValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 160, 30));

        lblCodigoPlate.setBackground(new java.awt.Color(255, 255, 255));
        lblCodigoPlate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblCodigoPlate.setForeground(new java.awt.Color(153, 0, 0));
        lblCodigoPlate.setText("Codigo:");
        lblCodigoPlate.setOpaque(true);
        getContentPane().add(lblCodigoPlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        txtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 110, 30));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 20));

        lblTypePlate.setBackground(new java.awt.Color(255, 255, 255));
        lblTypePlate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblTypePlate.setForeground(new java.awt.Color(153, 0, 0));
        lblTypePlate.setText(" Categoría del Plato:");
        lblTypePlate.setOpaque(true);
        getContentPane().add(lblTypePlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        listPlatoEspecial.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPnlPlatEspecial.setViewportView(listPlatoEspecial);

        getContentPane().add(scrollPnlPlatEspecial, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 240, 100));

        lblContenTitle.setBackground(new java.awt.Color(153, 0, 0));
        lblContenTitle.setFont(new java.awt.Font("Segoe UI Semibold", 1, 11)); // NOI18N
        lblContenTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblContenTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContenTitle.setOpaque(true);
        getContentPane().add(lblContenTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 810, 70));

        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 800, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        GUIMenuAdmin ins = new GUIMenuAdmin(this.servicioRestaurante);
        ins.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void cbxTipoPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoPlatoActionPerformed
        if (this.cbxTipoPlato.getSelectedItem().toString().equalsIgnoreCase("Plato del Dia")){
            this.setVisible(false);
            GUIRegPlatoD frame = new GUIRegPlatoD(this.servicioRestaurante);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_cbxTipoPlatoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (this.txtNombre.getText() != null && this.txtDescripcion.getText() != null && this.txtCodigo.getText() != null && this.txtValor.getText() != null) {
            MenuEspecial menuEspecial = new MenuEspecial(1);
            PlatoEspecial platoEspecial = new PlatoEspecial(Integer.valueOf(this.txtCodigo.getText()), this.txtNombre.getText(), Integer.valueOf(this.txtValor.getText()), this.txtDescripcion.getText(), menuEspecial.getId());
            try {
                String platoE = this.servicioRestaurante.savePlatoEspecial(platoEspecial);
                if (!platoE.equals("FALLO")) {
                    JOptionPane.showMessageDialog(null, "plato agregado con exito");
                    this.cbxTipoPlato.setSelectedIndex(0);
                    this.txtCodigo.setText("");
                    this.txtNombre.setText("");
                    this.txtValor.setText("");
                    this.txtDescripcion.setText("");
                    this.listar();
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "El plato ya esta registrado" + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9') evt.consume();
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        char c = evt.getKeyChar();
        if(c < '0' || c > '9') evt.consume(); 
    }//GEN-LAST:event_txtValorKeyTyped
    private void listar() throws Exception{
        int resId = 1;
        List<PlatoEspecial> lsEspecial = this.servicioRestaurante.listarMenuEspecial(resId);
        this.modelListEspecial.clear();
        for (PlatoEspecial lse : lsEspecial) {
            modelListEspecial.addElement("ID: " + lse.getId() + " NOMBRE: " + lse.getNombre()
                    + " DESCRIPCION: " + lse.getDescripcion() + " PRECIO: " + lse.getPrecio());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxTipoPlato;
    private javax.swing.JLabel lblCodigoPlate;
    private javax.swing.JLabel lblContenTitle;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombrePlate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTypePlate;
    private javax.swing.JLabel lblTypePrecio;
    private javax.swing.JList<String> listPlatoEspecial;
    private javax.swing.JScrollPane scrollPnlPlatEspecial;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
