package co.unicauca.restaurante.client.presentation;

import co.unicauca.restaurante.client.domain.clienteService;
import co.unicauca.restaurante.commons.domain.DiaEnum;
import co.unicauca.restaurante.commons.domain.MenuDia;
import co.unicauca.restaurante.commons.domain.PlatoDia;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo Gonzalez, Jhonny Rosero, Edynson Muñoz, James Silva, Jhonfer Ruiz
 */
public class GUIRegPlatoD extends javax.swing.JFrame {
    private clienteService servicioRestaurante;
    private DefaultListModel modelListDia;
    
    /**
     * Creates new form GUIRegPlato
     * @param servicioRestaurnate
     */
    public GUIRegPlatoD(clienteService servicioRestaurnate) {
        this.initComponents();
        this.setLocationRelativeTo(null);
        this.modelListDia = new DefaultListModel();
        this.jListPlatoDia.setModel(this.modelListDia);
        this.servicioRestaurante = servicioRestaurnate;
        try {
            this.listar();
        } catch (Exception ex) {
            Logger.getLogger(GUIRegPlatoD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        lblDescripcion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblBebida = new javax.swing.JLabel();
        txtBebida = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        txtValor = new javax.swing.JTextField();
        txtEntrada = new javax.swing.JTextField();
        txtPrincipio = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        lblEntrada = new javax.swing.JLabel();
        lblPrincipio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPlatoDia = new javax.swing.JList<>();
        txtCarne = new javax.swing.JTextField();
        lblBebida1 = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        cbxDia = new javax.swing.JComboBox<>();
        lblContenTitle = new javax.swing.JLabel();
        cbxTipoPlato = new javax.swing.JComboBox<>();
        lblCategoryPlate = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 450));
        setPreferredSize(new java.awt.Dimension(817, 370));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("REGISTRAR PLATO DIA");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 160, 30));

        txtDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 240, 50));

        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegistrar.setPreferredSize(new java.awt.Dimension(100, 200));
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 140, 50));

        lblDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        lblDescripcion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblDescripcion.setForeground(new java.awt.Color(153, 0, 0));
        lblDescripcion.setText("Descripción:");
        lblDescripcion.setOpaque(true);
        getContentPane().add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, -1, -1));

        lblNombre.setBackground(new java.awt.Color(255, 255, 255));
        lblNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(153, 0, 0));
        lblNombre.setText("Nombre:");
        lblNombre.setOpaque(true);
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        lblBebida.setBackground(new java.awt.Color(255, 255, 255));
        lblBebida.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblBebida.setForeground(new java.awt.Color(153, 0, 0));
        lblBebida.setText("Bebida:");
        lblBebida.setOpaque(true);
        getContentPane().add(lblBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        txtBebida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 160, 30));

        lblCodigo.setBackground(new java.awt.Color(255, 255, 255));
        lblCodigo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(153, 0, 0));
        lblCodigo.setText("Codigo:");
        lblCodigo.setOpaque(true);
        getContentPane().add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        txtCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 110, 30));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 20));

        txtValor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorKeyTyped(evt);
            }
        });
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, 140, 30));

        txtEntrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, 160, 30));

        txtPrincipio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtPrincipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 160, 30));

        lblValor.setBackground(new java.awt.Color(255, 255, 255));
        lblValor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblValor.setForeground(new java.awt.Color(153, 0, 0));
        lblValor.setText("Valor:");
        lblValor.setOpaque(true);
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, -1, -1));

        lblEntrada.setBackground(new java.awt.Color(255, 255, 255));
        lblEntrada.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblEntrada.setForeground(new java.awt.Color(153, 0, 0));
        lblEntrada.setText("Entrada:");
        lblEntrada.setOpaque(true);
        getContentPane().add(lblEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));

        lblPrincipio.setBackground(new java.awt.Color(255, 255, 255));
        lblPrincipio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblPrincipio.setForeground(new java.awt.Color(153, 0, 0));
        lblPrincipio.setText("Principio");
        lblPrincipio.setOpaque(true);
        getContentPane().add(lblPrincipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        jListPlatoDia.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListPlatoDia);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 270, 100));

        txtCarne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 160, 30));

        lblBebida1.setBackground(new java.awt.Color(255, 255, 255));
        lblBebida1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblBebida1.setForeground(new java.awt.Color(153, 0, 0));
        lblBebida1.setText("Carne:");
        lblBebida1.setOpaque(true);
        getContentPane().add(lblBebida1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        lblDia.setBackground(new java.awt.Color(255, 255, 255));
        lblDia.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblDia.setForeground(new java.awt.Color(153, 0, 0));
        lblDia.setText("Dia:");
        lblDia.setOpaque(true);
        getContentPane().add(lblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        cbxDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo" }));
        cbxDia.setBorder(null);
        getContentPane().add(cbxDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 180, 30));

        lblContenTitle.setBackground(new java.awt.Color(153, 0, 0));
        lblContenTitle.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        lblContenTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblContenTitle.setOpaque(true);
        getContentPane().add(lblContenTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 870, 70));

        cbxTipoPlato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Plato del Dia", "Plato Especial" }));
        cbxTipoPlato.setBorder(null);
        cbxTipoPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTipoPlatoActionPerformed(evt);
            }
        });
        getContentPane().add(cbxTipoPlato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 170, 40));

        lblCategoryPlate.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoryPlate.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblCategoryPlate.setForeground(new java.awt.Color(153, 0, 0));
        lblCategoryPlate.setText(" Categoría del Plato:");
        lblCategoryPlate.setOpaque(true);
        getContentPane().add(lblCategoryPlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 800, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        GUIMenuAdmin ins = new GUIMenuAdmin(this.servicioRestaurante);
        ins.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (this.txtNombre.getText()!=null && this.txtDescripcion.getText()!=null && this.txtCodigo.getText()!=null && this.txtValor.getText()!=null 
            && this.txtBebida.getText()!=null && this.txtPrincipio.getText()!=null && this.txtEntrada.getText()!=null && this.txtCarne.getText()!=null
            && !this.cbxDia.getSelectedItem().toString().equalsIgnoreCase("Seleccione")) {
            MenuDia menuDia = new MenuDia(1);
            PlatoDia platoDia = new PlatoDia(Integer.valueOf(this.txtCodigo.getText()), this.txtNombre.getText(),Integer.valueOf(this.txtValor.getText()), this.txtDescripcion.getText()
                                             , DiaEnum.valueOf(this.cbxDia.getSelectedItem().toString()), this.txtEntrada.getText(), this.txtPrincipio.getText(), this.txtCarne.getText()
                                             , this.txtBebida.getText(),menuDia.getId());
            try{
                String platoD = this.servicioRestaurante.savePlatoDia(platoDia);
                if (!platoD.equals("FALLO")){
                    JOptionPane.showMessageDialog(null, "Se registro el plato exitosamente");
                    this.cbxTipoPlato.setSelectedIndex(0);
                    this.cbxDia.setSelectedIndex(0);
                    this.txtCodigo.setText("");
                    this.txtNombre.setText("");
                    this.txtValor.setText("");
                    this.txtDescripcion.setText("");
                    this.txtBebida.setText("");
                    this.txtPrincipio.setText("");
                    this.txtEntrada.setText("");
                    this.txtCarne.setText("");
                    this.listar();  
                }
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "El plato ya esta registrado; Message: "+ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cbxTipoPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTipoPlatoActionPerformed
        if (this.cbxTipoPlato.getSelectedItem().toString().equalsIgnoreCase("Plato Especial")){
            this.setVisible(false);
            GUIRegPlato frame = new GUIRegPlato(this.servicioRestaurante);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_cbxTipoPlatoActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtValorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorKeyTyped
        char c = evt.getKeyChar();
        if(c<'0' || c>'9') evt.consume();
    }//GEN-LAST:event_txtValorKeyTyped
    
    private void listar() throws Exception{
        int resId = 1;
        List<PlatoDia> lsDia = this.servicioRestaurante.listarMenuDia(resId);
        this.modelListDia.clear();
        lsDia.forEach(ls -> {
            this.modelListDia.addElement("ID: " + ls.getId() + " NOMBRE: " + ls.getNombre()
                    + " DIA SEMANA: " + ls.getDiaSemana().name() + " DESCRIPCION: " + ls.getDescripcion()
                    + " PRECIO: " + ls.getPrecio() + " ENTRADA: " + ls.getEntrada()
                    + " PRINCIPIO" + ls.getPrincipio() + " CARNE: " + ls.getCarne() + " BEBIDA: " + ls.getBebida());
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxDia;
    private javax.swing.JComboBox<String> cbxTipoPlato;
    private javax.swing.JList<String> jListPlatoDia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBebida;
    private javax.swing.JLabel lblBebida1;
    private javax.swing.JLabel lblCategoryPlate;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblContenTitle;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrincipio;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtBebida;
    private javax.swing.JTextField txtCarne;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEntrada;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrincipio;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
